config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :fbo_accounts, only: [:index, :show] do
    resources :fbo_account_statements, as: :statements, path: :statements, only: [:index, :new, :create, :destroy] do
      post :import, on: :member
    end
    resources :fbo_account_transactions, as: :transactions, path: :transactions, only: [:index] do
      post :assign, on: :member
      post :expend, on: :member
      post :withdraw, on: :member
      get :new_withdrawal, on: :member
    end
  end

  resources :te_schemes, only: [:show] do
    resources :te_scheme_participants, as: :participants, path: :participants, only: [:index, :new, :create, :show]
    resources :te_scheme_contributions, as: :contributions, path: :contributions, only: [:index] do
      post :reaggregate, on: :member
    end
    resources :monthly_scheme_aggregates, as: :aggregates, path: :aggregates, only: [:index]

    post :reaggregate, on: :member
  end

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/fbo_account_transactions_controller.rb
class FboAccountTransactionsController < ApplicationController
  before_action :load_fbo_account
  before_action :load_transaction, only: [:assign, :expend, :new_withdrawal, :withdraw]

  def assign
    Te::IndividualContributionService.new.assign_fbo_transaction(@transaction, load_participant)
    reload_index
  end

  def expend
    Te::ExpenditureService.new.expend_fbo_transaction(@transaction)
    reload_index
  end

  def new_withdrawal
    @scheme = @account.te_scheme
  end

  def withdraw
    reason = params[:reason]
    raise "Reason for withdrawal is required" if reason.blank?

    Te::IndividualContributionService.new.withdraw_fbo_transaction(@transaction, load_participant, reason)
    redirect_to fbo_account_transactions_path(@account), notice: "Withdrawal successfully created."
  end

  def index
    @scheme = @account.te_scheme
  end

  private

  def reload_index
    load_fbo_account
    index
    render action: :index
  end

  def load_fbo_account
    @account = FboAccount.find(params[:fbo_account_id])
  end

  def load_transaction
    @transaction = @account.transactions.find(params[:id])
  end

  def load_participant
    @participant = @account.te_scheme.participants.find(params[:participant_id])
  end
end

app/views/fbo_account_transactions/index.html.erb
<article>
  <h1>FBO Account: <%= @account.name %></h1>
  <nav>
    <ul>
      <li><%= link_to "< home", root_path %></li>
      <li><%= link_to "TE scheme", @account.te_scheme %></li>
      <li><%= link_to "Statements", fbo_account_statements_path(@account) %></li>
    </ul>
  </nav>
  <h2>Transactions</h2>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Amount</th>
        <th>Memo</th>
        <th>Participant</th>
      </tr>
    </thead>
    <tbody>
      <% @account.transactions.date_order.each do |transaction| %>
        <tr>
          <td><%= transaction.posted_at.to_date.to_formatted_s(:short) %></td>
          <td class="money"><%= number_to_currency(transaction.amount) %></td>
          <td><%= transaction.memo %></td>
          <td>
            <% if transaction.money_in? %>
              <% if transaction.te_scheme_contribution %>
                <%= transaction.te_scheme_contribution.participant.name %>
              <% else %>
                <%= form_with url: assign_fbo_account_transaction_path(@account, transaction) do |form| %>
                  <%= form.select('participant_id', options_from_collection_for_select(@scheme.participants, 'id', 'name', nil), include_blank: true)  %>
                  <%= form.submit "Assign" %>
                <% end %>
              <% end %>
            <% elsif transaction.money_out? %>
              <% if !transaction.reconciled? %>
                <%= button_to "Expend", expend_fbo_account_transaction_path(@account, transaction), method: :post %>
                <div>or</div>
                <%= link_to "Withdrawal", new_withdrawal_fbo_account_transaction_path(@account, transaction)  %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
</article>

app/views/fbo_account_transactions/new_withdrawal.html.erb
<article>
  <h1>New FBO Account Statement</h1>
  <%= form_with url: withdraw_fbo_account_transaction_path(@account, @transaction) do |form| %>
    <p>
      <%= form.label :participant_id, "Participant" %>
      <%= form.select('participant_id', options_from_collection_for_select(@scheme.participants, 'id', 'name', nil), include_blank: true)  %>
    </p>
    <p>
      <%= form.label :reason, "Reason" %>
      <%= form.text_field :reason %>
    <p>
      <%= form.submit "Submit" %>
    </p>
  <% end %>
</article>