config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :fbo_accounts, only: [:index, :show] do
    resources :fbo_account_statements, as: :statements, path: :statements, only: [:index, :new, :create, :destroy] do
      post :import, on: :member
    end
    resources :fbo_account_transactions, as: :transactions, path: :transactions, only: [:index] do
      post :assign, on: :member
      post :expend, on: :member
      post :withdraw, on: :member
      get :new_withdrawal, on: :member
    end
  end

  resources :te_schemes, only: [:show] do
    resources :te_scheme_participants, as: :participants, path: :participants, only: [:index, :new, :create, :show]
    resources :te_scheme_contributions, as: :contributions, path: :contributions, only: [:index] do
      post :reaggregate, on: :member
    end
    resources :monthly_scheme_aggregates, as: :aggregates, path: :aggregates, only: [:index]

    post :reaggregate, on: :member
  end

  # Defines the root path route ("/")
  root "home#index"
end

app/models/te_scheme_participant.rb
class TeSchemeParticipant < ApplicationRecord
  belongs_to :te_scheme
  has_many :contributions, class_name: 'TeSchemeContribution'
  has_many :withdrawals, class_name: 'TeSchemeWithdrawal'
  has_many :monthly_aggregates, class_name: 'MonthlyParticipantAggregate'

  validates :name, presence: true

  def first_month
    first_date = contributions.minimum(:received_at)
    first_date.nil? ? Month.now : Month(first_date)
  end
end

app/controllers/te_scheme_participants_controller.rb
class TeSchemeParticipantsController < ApplicationController
  before_action :load_scheme
  before_action :load_participant, only: [:show]

  def index
    @participants = @scheme.participants
  end

  def new
    @participant = @scheme.participants.new
  end

  def create
    @participant = @scheme.participants.new create_params

    if @participant.save
      redirect_to te_scheme_participants_path(@scheme), notice: "Participant created"
    else
      render :new
    end
  end

  def show
    @monthly_aggregates = @participant.monthly_aggregates.closed
    @current_aggregate = @participant.monthly_aggregates.current_closed
    @monthly_aggregate = @scheme.monthly_aggregates.current_closed
  end

  private

  def create_params
    params.require(:te_scheme_participant).permit(:name)
  end

  def load_scheme
    @scheme = TeScheme.find params[:te_scheme_id]
  end

  def load_participant
    @participant = @scheme.participants.find params[:id]
  end
end

app/views/te_scheme_participants/index.html.erb
<article>
  <h1>TE Scheme Participants: <%= @scheme.name %></h1>
  <nav>
    <ul>
      <li><%= link_to "< back to Scheme", @scheme %></li>
      <li><%= link_to "New", new_te_scheme_participant_path(@scheme) %></li>
    </ul>
  </nav>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Links</th>
      </tr>
    </thead>
    <tbody>
      <% @participants.each do |participant| %>
        <tr>
          <td><%= participant.name %></td>
          <td><%= link_to "show", te_scheme_participant_path(@scheme, participant) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</article>

app/views/te_scheme_participants/new.html.erb
<article>
  <h1>New TE Participant</h1>
  <%= form_with model: @participant do |form| %>
    <p>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </p>
    <p>
      <%= form.submit "Submit" %>
    </p>
  <% end %>
</article>

app/views/te_scheme_participants/show.html.erb
<article>
  <h1>Participant: <%= @participant.name %></h1>
  <nav>
    <ul>
      <li><%= link_to "< home", root_path %></li>
      <li><%= link_to "TE scheme", @scheme %></li>
    </ul>
  </nav>
  <h2>Months</h2>
  <table>
    <thead>
      <tr>
        <th>Month</th>
        <th>Deposit Total</th>
        <th>Demurrage</th>
        <th>TE Issue</th>
        <th>TE Withdrawal</th>
        <th>TE Delta</th>
        <th>TE Max Balance</th>
        <th>TE Value</th>
      </tr>
    </thead>
    <tbody>
      <% @monthly_aggregates.each do |ma| %>
        <tr>
          <td><%= ma.month %></td>
          <td class="money"><%= number_to_currency ma.deposit_total %></td>
          <td class="money"><%= number_to_currency ma.demurrage %></td>
          <td class="money"><%= number_to_currency ma.te_issue %></td>
          <td class="money"><%= number_to_currency ma.te_withdrawal %></td>
          <td class="money"><%= number_to_currency ma.te_delta %></td>
          <td class="money"><%= number_to_currency ma.te_max_balance %></td>
          <td class="money"><%= number_to_currency ma.te_value %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h2>Formatted for Email</h2>
  <h3>This Month: <%= @current_aggregate.month %></h3>
  <h4>Your ingoings:</h4>
  <p>
    Deposit Total: <%= number_to_currency @current_aggregate.deposit_total %><br>
    TE Issue: <%= number_to_currency @current_aggregate.te_issue %><br>

  </p>
  <h4>Your outgoings:</h4>
  <p>
  Demurrage: <%= number_to_currency @current_aggregate.demurrage %><br></p>
  <h4>Your Totals:</h4>
  <p>
    TE Max Balance: <%= number_to_currency @current_aggregate.te_max_balance %><br>
    TE Value: <%= number_to_currency @current_aggregate.te_value %>
  </p>
  <h4>Scheme totals:</h4>
  <p>
    TE Max: <%= number_to_currency @monthly_aggregate.te_total %><br>
    Liquidy: <%= number_to_percentage @monthly_aggregate.liquidity * 100.0, precision: 1 %><br />
    TE Total Value: <%= number_to_currency @monthly_aggregate.te_total_value %><br>

  </p>

</article>