config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :fbo_accounts, only: [:index, :show] do
    resources :fbo_account_statements, as: :statements, path: :statements, only: [:index, :new, :create, :destroy] do
      post :import, on: :member
    end
    resources :fbo_account_transactions, as: :transactions, path: :transactions, only: [:index] do
      post :assign, on: :member
      post :expend, on: :member
      post :withdraw, on: :member
      get :new_withdrawal, on: :member
    end
  end

  resources :te_schemes, only: [:show] do
    resources :te_scheme_participants, as: :participants, path: :participants, only: [:index, :new, :create, :show]
    resources :te_scheme_contributions, as: :contributions, path: :contributions, only: [:index] do
      post :reaggregate, on: :member
    end
    resources :monthly_scheme_aggregates, as: :aggregates, path: :aggregates, only: [:index]

    post :reaggregate, on: :member
  end

  # Defines the root path route ("/")
  root "home#index"
end

app/models/fbo_account_statement.rb
class FboAccountStatement < ApplicationRecord
  belongs_to :fbo_account
  has_many :transactions, class_name: 'FboAccountTransaction', dependent: :destroy

  VALID_FORMATS = ['ofx'].freeze

  validates :original_filename, presence: true, on: :create
  validates :file_contents, presence: true, on: :create
  validates :format, inclusion: { in: VALID_FORMATS }, allow_nil: true

  def file=(value)
    return if value.nil?

    self.original_filename = value.original_filename
    self.file_contents = value.read
  end

  def import!
    Importers.for(format).new.import(file_contents, self)
    update! imported_at: Time.current
  end

  private

  before_validation on: :create do
    self.format = File.extname(original_filename).delete('.')
  end
end

app/controllers/fbo_account_statements_controller.rb
class FboAccountStatementsController < ApplicationController
  before_action :load_account

  def index
    @statements = @account.statements
  end

  def new
    @statement = FboAccountStatement.new
  end

  def create
    @statement = @account.statements.build(create_params)
    if @statement.save
      redirect_to action: :index
    else
      raise @statement.errors.inspect
      render action: :new
    end
  end

  def import
    load_statement
    @statement.import!
    redirect_to action: :index
  end

  def destroy
    load_statement
    @statement.destroy
    redirect_to action: :index
  end

  private

  def load_statement
    @statement = @account.statements.find params[:id]
  end

  def load_account
    @account = FboAccount.find params[:fbo_account_id]
  end

  def create_params
    params.require(:fbo_account_statement).permit(:file)
  end
end

app/views/fbo_account_statements/index.html.erb
<article>
  <h1>FBO Account Statements: <%= @account.name %></h1>
  <nav>
    <ul>
      <li><%= link_to "< back to Account", fbo_account_path(@account) %></li>
      <li><%= link_to "New", new_fbo_account_statement_path(@account) %></li>
    </ul>
  </nav>

  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Filename</th>
        <th>Uploaded</th>
        <th>Format</th>
        <th>Imported</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @statements.each do |statement| %>
        <tr>
          <td><%= statement.id %></td>
          <td><%= statement.original_filename %></td>
          <td><%= statement.created_at.to_formatted_s(:short) %></td>
          <td><%= statement.format %></td>
          <td><%= statement.imported_at&.to_formatted_s(:short) %></td>
          <td><%= button_to "import", import_fbo_account_statement_path(@account, statement) %> <%= button_to "delete", fbo_account_statement_path(@account, statement), method: :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</article>

app/views/fbo_account_statements/new.html.erb
<article>
  <h1>New FBO Account Statement</h1>
  <%= form_with model: @statement do |form| %>
    <p>
      <%= form.label :file, "Upload file" %>
      <%= form.file_field :file %>
    </p>
    <p>
      <%= form.submit "Submit" %>
    </p>
  <% end %>
</article>