config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :fbo_accounts, only: [:index, :show] do
    resources :fbo_account_statements, as: :statements, path: :statements, only: [:index, :new, :create, :destroy] do
      post :import, on: :member
    end
    resources :fbo_account_transactions, as: :transactions, path: :transactions, only: [:index] do
      post :assign, on: :member
      post :expend, on: :member
      post :withdraw, on: :member
      get :new_withdrawal, on: :member
    end
  end

  resources :te_schemes, only: [:show] do
    resources :te_scheme_participants, as: :participants, path: :participants, only: [:index, :new, :create, :show]
    resources :te_scheme_contributions, as: :contributions, path: :contributions, only: [:index] do
      post :reaggregate, on: :member
    end
    resources :monthly_scheme_aggregates, as: :aggregates, path: :aggregates, only: [:index]

    post :reaggregate, on: :member
  end

  # Defines the root path route ("/")
  root "home#index"
end

app/models/te_scheme.rb
class TeScheme < ApplicationRecord
  belongs_to :fbo_account
  has_many :participants, class_name: 'TeSchemeParticipant'
  has_many :contributions, class_name: 'TeSchemeContribution', through: :participants
  has_many :expenditures, class_name: 'TeSchemeExpenditure'
  has_many :monthly_aggregates, class_name: 'MonthlySchemeAggregate'
  has_many :monthly_participant_aggregates, class_name: 'MonthlyParticipantAggregate', through: :participants, source: :monthly_aggregates

  def first_month
    first_date = contributions.minimum(:received_at)
    first_date.nil? ? Month.now : Month(first_date)
  end
end

app/controllers/te_schemes_controller.rb
class TeSchemesController < ApplicationController
  before_action :load_scheme, only: [:show, :reaggregate]

  def show
   @monthly_aggregate = @scheme.monthly_aggregates.current_closed
  end

  def reaggregate
    Te::SchemeAggregateService.new.aggregate_participants_and_scheme(@scheme)
    redirect_to @scheme
  end

  private

  def load_scheme
    @scheme = TeScheme.find(params[:id])
  end
end

app/views/te_schemes/show.html.erb
<article>
  <h1>TE Scheme: <%= @scheme.name %></h1>
  <nav>
    <ul>
      <li><%= link_to "< home", root_path %></li>
      <li><%= link_to "FBO account", @scheme.fbo_account %></li>
      <li><%= link_to "Participants", te_scheme_participants_path(@scheme) %></li>
      <li><%= link_to "Contributions", te_scheme_contributions_path(@scheme) %></li>
      <li><%= link_to "Months", te_scheme_aggregates_path(@scheme) %></li>
      <li><%= button_to "Reaggregate", reaggregate_te_scheme_path(@scheme) %></li>
    </ul>
  </nav>
  <% if @monthly_aggregate %>
    <table class="vertical">
      <tbody>
        <tr>
          <th>Participants</th>
          <td class="number"><%= @scheme.participants.count %></td>
        </tr>
        <tr>
          <th>Date</th>
          <td><%= @monthly_aggregate.month.end_date %></td>
        </tr>
        <tr>
          <th>TE Total</th>
          <td class="money"><%= number_to_currency @monthly_aggregate.te_total %></td>
        </tr>
        <tr>
          <th>FBO Funds Total</th>
          <td class="money"><%= number_to_currency @monthly_aggregate.fbo_funds_total %></td>
        </tr>
        <tr>
          <th>Liquidity</th>
          <td class="number"><%= number_to_percentage @monthly_aggregate.liquidity * 100.0, precision: 1 %></td>
        </tr>
        <tr>
          <th>TE Total Value</th>
          <td class="money"><%= number_to_currency @monthly_aggregate.te_total_value %></td>
        </tr>
        <tr>
          <th>TE Payout</th>
          <td class="money"><%= number_to_currency number_with_precision @monthly_aggregate.te_value_ratio, precision: 2 %></td>
        </tr>
      </tbody>
    </table>
    <h2>Streams</h2>
    <table>
      <thead>
        <tr>
          <th>Bank Mortgage</th>
          <th>Transitional Equity</th>
          <th>Collective Stewardship</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="money"><%= number_to_currency @monthly_aggregate.stream_dollar_value(:bm) %></td>
          <td class="money"><%= number_to_currency @monthly_aggregate.stream_dollar_value(:te) %></td>
          <td class="money"><%= number_to_currency @monthly_aggregate.stream_dollar_value(:cs) %></td>
        </tr>
        <tr>
          <td class="number"><%= number_to_percentage @monthly_aggregate.stream_ratio(:bm) * 100.0, precision: 1 %></td>
          <td class="number"><%= number_to_percentage @monthly_aggregate.stream_ratio(:te) * 100.0, precision: 1 %></td>
          <td class="number"><%= number_to_percentage @monthly_aggregate.stream_ratio(:cs) * 100.0, precision: 1 %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
</article>